// Auto-generated by scripts/gen-changelog.mjs — do not edit by hand.
export interface ChangelogEntry {
  version: string
  date: string
  title: string
  sha: string
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.28",
    "date": "2026-09-26",
    "title": "serve the marketing landing page at /landing",
    "sha": "6e5ea7a5a7fd3a3834f684e37bce1b8dacdd7889"
  },
  {
    "version": "0.1.26",
    "date": "2026-09-26",
    "title": "full clone depth so version and changelog derive from real history",
    "sha": "a3f6f0f70cde6d71724a2e8b436cb623ac15f8fc"
  },
  {
    "version": "0.1.25",
    "date": "2026-09-26",
    "title": "add @types/node; add changelog page auto-generated from git",
    "sha": "75cc7b103403d278df4cdb90649fad96180e9330"
  },
  {
    "version": "0.1.24",
    "date": "2026-09-26",
    "title": "dark mode, next-feed prediction, and auto versioning",
    "sha": "4913106ffa912737f71d3b0e52f1c35e95dfd33a"
  },
  {
    "version": "0.1.23",
    "date": "2026-09-26",
    "title": "password recovery via email-otp reset in account card",
    "sha": "19d85d75ae53de0d11ed43d9eeb922d367e9ceb3"
  },
  {
    "version": "0.1.22",
    "date": "2026-09-24",
    "title": "move buy me a coffee to bottom of settings; add sidebar and bottom-bar links",
    "sha": "6010e4b3cccd5dc1a410c9dd12da07ed74ec37fe"
  },
  {
    "version": "0.1.21",
    "date": "2026-09-24",
    "title": "buy me a coffee button at the top of settings",
    "sha": "8d83464a6c7ecc9e931f3af3ada6f53edbfc1c02"
  },
  {
    "version": "0.1.20",
    "date": "2026-09-23",
    "title": "smooth subtle fade-slide transition between pages",
    "sha": "5af5d2c768231e1f79e093dc6a555da0dd1fd413"
  },
  {
    "version": "0.1.19",
    "date": "2026-09-23",
    "title": "stacked sleep/feed/awake trend columns; collapse bottom nav to 2 rows",
    "sha": "291b495fbaa2726c35b03697f8d9076fab84b20a"
  },
  {
    "version": "0.1.18",
    "date": "2026-09-23",
    "title": "lucide icons, desktop sidebar + wider grids, remove header sign out",
    "sha": "4f2bfda3fb2b4b5c98c26f91cbb42707ca9689ca"
  },
  {
    "version": "0.1.17",
    "date": "2026-09-23",
    "title": "live SSE sync so partners see each other's changes instantly",
    "sha": "4ed403090467bd9cd474ddc6fefae35d410cb33a"
  },
  {
    "version": "0.1.16",
    "date": "2026-09-22",
    "title": "keep content clear of bottom bar; poll for live multi-user sync",
    "sha": "47495f9ef0c933cb8cc30baf8ac7d022b2f24ace"
  },
  {
    "version": "0.1.15",
    "date": "2026-09-22",
    "title": "merge duplicate children on family join; allow deleting a child",
    "sha": "a5fdcce91af0c8a83c722d8f360a2f3265b45129"
  },
  {
    "version": "0.1.14",
    "date": "2026-09-22",
    "title": "add Sign out button to the app bar next to Settings",
    "sha": "44d4f02a459e05854eac14482594e1ac45d00005"
  },
  {
    "version": "0.1.13",
    "date": "2026-09-22",
    "title": "auto-restore household on sign-in so the account view shows on any device",
    "sha": "6cceb2bb016e301ce7aa50bd795e8e92c76b0588"
  },
  {
    "version": "0.1.12",
    "date": "2026-09-22",
    "title": "fetch session JWT directly; Neon adapter token() uses a stale cache after sign-up",
    "sha": "af2a8ce9dab1d3bbaf190e793a518a185b381e9f"
  },
  {
    "version": "0.1.11",
    "date": "2026-09-22",
    "title": "avoid readwrite transaction inside liveQuery for sync state",
    "sha": "c8c17cd7b7a2793243401a320f637fac701d2a13"
  },
  {
    "version": "0.1.10",
    "date": "2026-09-22",
    "title": "opt-in family sync via Neon Auth",
    "sha": "f601447f62e28142ca966b28a56a5ff87081d93a"
  },
  {
    "version": "0.1.9",
    "date": "2026-09-22",
    "title": "neon sync function for family account sharing",
    "sha": "be41282a0ad6bb1aea3bb3cab80e3e92dff82eec"
  },
  {
    "version": "0.1.8",
    "date": "2026-09-22",
    "title": "migrate new records to uuid ids while keeping ++id keys",
    "sha": "01fc1a11f47288dc3c69446f65add986072e976e"
  },
  {
    "version": "0.1.7",
    "date": "2026-09-22",
    "title": "merge adjacent sleep entries and add trends calendar view",
    "sha": "a662444f17b1ae384db433cd674e2f3a21b3b9d8"
  },
  {
    "version": "0.1.6",
    "date": "2026-09-22",
    "title": "lock-screen background push notifications",
    "sha": "6e943fa46b70489dca8152f5e4863e80a667725d"
  },
  {
    "version": "0.1.5",
    "date": "2026-09-22",
    "title": "selected-child update loop blanking subpages",
    "sha": "3e7e7aacb09cedcf1dd18613fbb84092105ab68c"
  },
  {
    "version": "0.1.2",
    "date": "2026-09-22",
    "title": "onboarding routing race bouncing users back to setup",
    "sha": "6301df368da4a705a3e062dfb91fc22e0d88e773"
  },
  {
    "version": "0.1.1",
    "date": "2026-09-22",
    "title": "local-first baby & parent tracker PWA (MVP)",
    "sha": "81177b85c3ce841ff147107d27057277e1fe1fbf"
  }
]
