// Auto-generated by scripts/gen-changelog.mjs — do not edit by hand.
export interface ChangelogEntry {
  version: string
  date: string
  title: string
  sha: string
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    "version": "0.1.53",
    "date": "2026-10-08",
    "title": "add quick ml adjust buttons to pump log",
    "sha": "3f177e724fd9855b058838c0a83cc465d3b5e0ce"
  },
  {
    "version": "0.1.52",
    "date": "2026-10-07",
    "title": "add quick ml adjust buttons to bottle log",
    "sha": "9bc3e784f5bf6d76df0d57ba2db1fb3cea1e5911"
  },
  {
    "version": "0.1.50",
    "date": "2026-10-07",
    "title": "add sign-in/create-account join card to onboarding",
    "sha": "5d61264ce62bbfd6d787fa7d7e8804da0e84d315"
  },
  {
    "version": "0.1.48",
    "date": "2026-10-07",
    "title": "remap event childIds when adopting ids",
    "sha": "ac7e88e706729c49ab037d6a125efb4a27d75f2f"
  },
  {
    "version": "0.1.47",
    "date": "2026-10-07",
    "title": "improve push permission handling on Android and harden cron dispatch",
    "sha": "e0133fd66de46299e2da1dc67f85ef6fb53f2421"
  },
  {
    "version": "0.1.46",
    "date": "2026-10-06",
    "title": "noise machine with 10 synthesized sounds, fade, sleep-timer integration",
    "sha": "b0144184067f24e3e95316d4dec0d67a7d1462b5"
  },
  {
    "version": "0.1.45",
    "date": "2026-10-06",
    "title": "add settings and about links to the bottom nav, drop the coffee button",
    "sha": "a0d447bc80e412157a1b9b85b6c2ac03e9beac0c"
  },
  {
    "version": "0.1.43",
    "date": "2026-10-05",
    "title": "slide and fade deleted list rows out instead of vanishing",
    "sha": "2126c8b6e19672ab0b8ff1d5af39321c26fc8170"
  },
  {
    "version": "0.1.42",
    "date": "2026-10-05",
    "title": "vibrate reminders, disable quiet hours, and enter baby weight in lb and oz",
    "sha": "bedb14859570a52bf9064ad7ec1140a97f40d895"
  },
  {
    "version": "0.1.41",
    "date": "2026-10-05",
    "title": "follow unit settings everywhere and log optional nursing volume",
    "sha": "69ea288a3f5c0a048da497cba7f3ab4a2ef56dbe"
  },
  {
    "version": "0.1.40",
    "date": "2026-10-05",
    "title": "stop duplicate feeding timers and resume naps within five minutes",
    "sha": "4ff4d0487ba6e02ddcc265654abd2ac0353fc2a3"
  },
  {
    "version": "0.1.39",
    "date": "2026-10-05",
    "title": "edit logged entries and stop the page jumping between timer actions",
    "sha": "0656049e734a5d85540b6f9ba1461d245eed14ce"
  },
  {
    "version": "0.1.38",
    "date": "2026-10-05",
    "title": "dark mode styling for diaper quick-log buttons",
    "sha": "179d33d9c38799efa430f14de127f28030b7f337"
  },
  {
    "version": "0.1.37",
    "date": "2026-10-04",
    "title": "log a finished nursing session with a backdated start time",
    "sha": "609f42b2e314bc5256668ec6f7a2feb41ae390f6"
  },
  {
    "version": "0.1.36",
    "date": "2026-10-04",
    "title": "custom reminder length in minutes and editable titles",
    "sha": "ec2059ad503a2ae6290a32d8cf3a129a6fb7f338"
  },
  {
    "version": "0.1.35",
    "date": "2026-09-26",
    "title": "consolidate firsts into milestones and drop the guides feature",
    "sha": "2083d373e1bd4ddc52aedf5c44070617824215ba"
  },
  {
    "version": "0.1.34",
    "date": "2026-09-26",
    "title": "portal sheets to body so the page animation cannot displace them",
    "sha": "93759003cf883f6df35b24aa024967a44545d63d"
  },
  {
    "version": "0.1.32",
    "date": "2026-09-26",
    "title": "add a theme toggle to the onboarding screen",
    "sha": "4e9707e0e5376ebde3d6cf9d40bdf226a71d3ebe"
  },
  {
    "version": "0.1.31",
    "date": "2026-09-26",
    "title": "repair concatenated .gitignore rules and make the e2e harness runnable",
    "sha": "d89238ae68c3290964e874b9e960a92ac32d243d"
  },
  {
    "version": "0.1.30",
    "date": "2026-09-26",
    "title": "point the landing page contact form at support@lulla.dev",
    "sha": "bccc894609d1525a15bb6a3a2dd047d62671b99f"
  },
  {
    "version": "0.1.29",
    "date": "2026-09-26",
    "title": "rekey numeric ids row-driven so an owner's child is never dropped",
    "sha": "4ba271b62912944c099047cf320c375be4d1445d"
  },
  {
    "version": "0.1.28",
    "date": "2026-09-26",
    "title": "serve the marketing landing page at /landing",
    "sha": "6e5ea7a5a7fd3a3834f684e37bce1b8dacdd7889"
  },
  {
    "version": "0.1.26",
    "date": "2026-09-26",
    "title": "full clone depth so version and changelog derive from real history",
    "sha": "a3f6f0f70cde6d71724a2e8b436cb623ac15f8fc"
  },
  {
    "version": "0.1.25",
    "date": "2026-09-26",
    "title": "add @types/node; add changelog page auto-generated from git",
    "sha": "75cc7b103403d278df4cdb90649fad96180e9330"
  },
  {
    "version": "0.1.24",
    "date": "2026-09-26",
    "title": "dark mode, next-feed prediction, and auto versioning",
    "sha": "4913106ffa912737f71d3b0e52f1c35e95dfd33a"
  },
  {
    "version": "0.1.23",
    "date": "2026-09-26",
    "title": "password recovery via email-otp reset in account card",
    "sha": "19d85d75ae53de0d11ed43d9eeb922d367e9ceb3"
  },
  {
    "version": "0.1.22",
    "date": "2026-09-24",
    "title": "move buy me a coffee to bottom of settings; add sidebar and bottom-bar links",
    "sha": "6010e4b3cccd5dc1a410c9dd12da07ed74ec37fe"
  },
  {
    "version": "0.1.21",
    "date": "2026-09-24",
    "title": "buy me a coffee button at the top of settings",
    "sha": "8d83464a6c7ecc9e931f3af3ada6f53edbfc1c02"
  },
  {
    "version": "0.1.20",
    "date": "2026-09-23",
    "title": "smooth subtle fade-slide transition between pages",
    "sha": "5af5d2c768231e1f79e093dc6a555da0dd1fd413"
  },
  {
    "version": "0.1.19",
    "date": "2026-09-23",
    "title": "stacked sleep/feed/awake trend columns; collapse bottom nav to 2 rows",
    "sha": "291b495fbaa2726c35b03697f8d9076fab84b20a"
  },
  {
    "version": "0.1.18",
    "date": "2026-09-23",
    "title": "lucide icons, desktop sidebar + wider grids, remove header sign out",
    "sha": "4f2bfda3fb2b4b5c98c26f91cbb42707ca9689ca"
  },
  {
    "version": "0.1.17",
    "date": "2026-09-23",
    "title": "live SSE sync so partners see each other's changes instantly",
    "sha": "4ed403090467bd9cd474ddc6fefae35d410cb33a"
  },
  {
    "version": "0.1.16",
    "date": "2026-09-22",
    "title": "keep content clear of bottom bar; poll for live multi-user sync",
    "sha": "47495f9ef0c933cb8cc30baf8ac7d022b2f24ace"
  },
  {
    "version": "0.1.15",
    "date": "2026-09-22",
    "title": "merge duplicate children on family join; allow deleting a child",
    "sha": "a5fdcce91af0c8a83c722d8f360a2f3265b45129"
  },
  {
    "version": "0.1.14",
    "date": "2026-09-22",
    "title": "add Sign out button to the app bar next to Settings",
    "sha": "44d4f02a459e05854eac14482594e1ac45d00005"
  },
  {
    "version": "0.1.13",
    "date": "2026-09-22",
    "title": "auto-restore household on sign-in so the account view shows on any device",
    "sha": "6cceb2bb016e301ce7aa50bd795e8e92c76b0588"
  },
  {
    "version": "0.1.12",
    "date": "2026-09-22",
    "title": "fetch session JWT directly; Neon adapter token() uses a stale cache after sign-up",
    "sha": "af2a8ce9dab1d3bbaf190e793a518a185b381e9f"
  },
  {
    "version": "0.1.11",
    "date": "2026-09-22",
    "title": "avoid readwrite transaction inside liveQuery for sync state",
    "sha": "c8c17cd7b7a2793243401a320f637fac701d2a13"
  },
  {
    "version": "0.1.10",
    "date": "2026-09-22",
    "title": "opt-in family sync via Neon Auth",
    "sha": "f601447f62e28142ca966b28a56a5ff87081d93a"
  },
  {
    "version": "0.1.9",
    "date": "2026-09-22",
    "title": "neon sync function for family account sharing",
    "sha": "be41282a0ad6bb1aea3bb3cab80e3e92dff82eec"
  },
  {
    "version": "0.1.8",
    "date": "2026-09-22",
    "title": "migrate new records to uuid ids while keeping ++id keys",
    "sha": "01fc1a11f47288dc3c69446f65add986072e976e"
  },
  {
    "version": "0.1.7",
    "date": "2026-09-22",
    "title": "merge adjacent sleep entries and add trends calendar view",
    "sha": "a662444f17b1ae384db433cd674e2f3a21b3b9d8"
  },
  {
    "version": "0.1.6",
    "date": "2026-09-22",
    "title": "lock-screen background push notifications",
    "sha": "6e943fa46b70489dca8152f5e4863e80a667725d"
  },
  {
    "version": "0.1.5",
    "date": "2026-09-22",
    "title": "selected-child update loop blanking subpages",
    "sha": "3e7e7aacb09cedcf1dd18613fbb84092105ab68c"
  },
  {
    "version": "0.1.2",
    "date": "2026-09-22",
    "title": "onboarding routing race bouncing users back to setup",
    "sha": "6301df368da4a705a3e062dfb91fc22e0d88e773"
  },
  {
    "version": "0.1.1",
    "date": "2026-09-22",
    "title": "local-first baby & parent tracker PWA (MVP)",
    "sha": "81177b85c3ce841ff147107d27057277e1fe1fbf"
  }
]
